### ISSUE TITLE
Connected, but returns "check system busy" with any command sent.

### ISSUE THREAD

**Issue by PlastiBots** [enclot/GoProBLE#2]
Hi.  First, thanks for putting this library together..   I've been fighting for days to try to get my GP Hero 7 connected (tried many other libraries). Finally with the help of this and one from [@konradIT](https://github.com/KonradIT/gopro32) I am connected to my Hero.  However, it seems to have issues with any command sent. Always returns **"check system busy"**  in the Serial Monitor.  I can confirm that it shows connected on the GoPro (prefs>connections).  I can also get a response when clicking the button to take a photo, but any attempt to set the shutter etc, fails with the above noted error.  Only changes I made is using an M5Atom Lite ESP32 and it's button.  Any thoughts on this?

```
#include "M5Atom.h"
#include <GoProBLE.h>

GoProBLE goproBle;
uint32_t ticked;

void setup()
{
  Serial.begin(115200);

  goproBle.scanAsync(5);
  delay(1000);

  goproBle.connect();
  goproBle.enableStatusResponse();

  ticked = millis();
}


void loop()
{
  
  if (M5.Btn.wasPressed())
  {

    if (goproBle.isConnected()) 
    {
      if (!goproBle.isSystemBusy()) {
        goproBle.shutterOn();
      } else {
        goproBle.shutterOff();
      }
      Serial.print("Batt % : ");Serial.println(goproBle.getBatteryPercentage() );
    }
  }


  if (millis() - ticked > 3000) {
    goproBle.checkSystemBusyAsync();
    goproBle.checkSystemHotAsync();
    goproBle.checkBatteryPercentageAsync();

    ticked = millis();
  }

  M5.update();    //Read the press state of the key. 
  delay(10);

}
```

**Comment by enclot** [comment]
Thanks for the comment.

Unfortunately, I don't have a Hero8, so I checked it with my friend's Hero9Black.

I had the same problem.

However, for some reason, there are times when I can connect to it and when I do
"notify status callback" log is displayed.
I think perhaps enableStatusResponse() is not being executed at the right time.

put delay() after goproBle.connect();
in setup() will work for now.

```
void setup()
{
  Serial.begin(115200);
  goproBle.scanAsync(5);
  delay(1000);

  goproBle.connect();
  delay(1000);
  goproBle.enableStatusResponse();
  

  ticked = millis();
}

```
I'm sorry for the confusing message output.
I hope to fix it soon.

**Comment by PlastiBots** [comment]
Thanks for the suggestion, but sadly it still doesn't work (also note that I have a GoPro Hero 7).   I tried with both a 1 and 5 second delay in Setup() - code and Serial output below.  Any other thoughts? It's as if my GP is not even seeing the requests?
Is there some debugging I can add to see more around responses in the NimBLE library?

```
void setup()
{
  Serial.begin(115200);
  goproBle.scanAsync(5);
  delay(1000);
  goproBle.connect();
  delay(1000);
  goproBle.enableStatusResponse();
  ticked = millis(); 
}
```

```
Service Data:
UUID: 0xfea6, Data: i⸮y⸮9006
Stop Scan
Scan Ended.cpp static
New client created
Connected to: dd:60:6d:55:6f:c9
RSSI: -35
enable notify
Wrote Shutter:Off
Batt % : 0
Wrote Shutter:Off
Batt % : 0
```

**Comment by enclot** [comment]
I was wrong about hero8.

I think you are not getting any notifications from your gopro.
When you get a notification, you will see "notify status callback" in the log.
Since you are not getting any notifications, isSystemBusy() is set to false.

To see the response from the NimBLE library, you can just add Serial.print() directly to GoProBLE.cpp

**Comment by PlastiBots** [comment]
I noticed that the below function does not return it's Serial print statement.  As it seems to be the only function that sets systemBusy (which feeds into isSystemBusy() ), it looks like it doesn't get called, so going to trace it back to see why.

```
void GoProBLE::notifyedStatusCB(NimBLERemoteCharacteristic *pRemoteCharacteristic, uint8_t *pData,
                                size_t length, bool isNotify)
{
    Serial.print("notify status callback    ");
    Serial.println(length);
    ..................
```

**Comment by PlastiBots** [comment]
Tracing it back and looking at the _enableStatusResponse()_ function, I can see that it seems successful on  _subscribe(true, cb)_, .  I assume the _auto cb_ call binds the response to _notifyedStatusCB_ but don't really understand that statement and how to interpret what will happen.  Is there a way I can check the return responses from the GoPro?  Also assuming it's working right, any suggestions on how I can dump more detailed logs? It seems like my GP is simply not responding?  

```
bool GoProBLE::enableStatusResponse()
{
    if (pClient->isConnected())
    {
		NimBLERemoteService *pService = pClient->getService("fea6");
        if (pService != nullptr)
        {
			NimBLERemoteCharacteristic *pChrNotify = pService->getCharacteristic(NimBLEUUID("b5f90077-aa8d-11e3-9046-0002a5d5c51b"));
            if (pChrNotify->canNotify())
            {
                Serial.println("enable notify");

                auto cb = std::bind(&GoProBLE::notifyedStatusCB, this, std::placeholders::_1, std::placeholders::_2, std::placeholders::_3, std::placeholders::_4);

                if (!pChrNotify->subscribe(true, cb))
                {
                    /** Disconnect if subscribe failed */
                    pClient->disconnect();
                    return false;
                }
				//else {Serial.println("Notify Subscribed");}
            }
        }
        else
        {
            
			return false;
        }
    }

    return false;
}
```

**Comment by enclot** [comment]
Can you check the return value of pClient->secureConnection() in GoProBLE::connect()?

If false, you will not be notified
I don't know why, but it can be false.

Sometimes turning off the Gopro and trying again will work.

**Comment by enclot** [comment]
I don't know the cause.
In hero9, once paired, secureConnection will return false from the pairing screen.
If not on the pairing screen, it's OK.
No problem with hero6.

**Comment by PlastiBots** [comment]
When I output the result of pClient->secureConnection(); I get a 0, but not sure what that means?

**Comment by enclot** [comment]
It is need secure connection.
https://h2zero.github.io/esp-nimble-cpp/class_nim_b_l_e_client.html#a79935ecbe94f2a41e0106d011edafac4

If it works correctly, this will be true
You might try pairing with the gopro again.

I know it can be false, but I can't figure out why.

**Comment by PlastiBots** [comment]
It sounds like this is the issue then.. Unfortunately, it's beyond my level for trying to figure out how to get it working. Again, thanks for your help.  Good news is I managed to get it working using WiFi with a twist.. Details are [here](https://github.com/aster94/GoProControl/issues/40#issuecomment-998717328).

**Comment by enclot** [comment]
Glad you found a solution.
